### ISSUE TITLE
Running Benchmark MNIST Model with Sharding Overrides

### ISSUE THREAD

**Issue by vcanicTT** [tenstorrent/tt-mlir#1112]
We have an error when we run the model with sharding overrides.

Here, we run simple MNIST benchmark model with passed sharding overrides through the tt-forge-fe. All configurations/overrides are hard-coded within the tt-forge-fe stack. They're not passed via the model, because we don't have the mechanism for passing them in that way.

Forge setup, docs: `https://docs.tenstorrent.com/tt-forge-fe/build.html`

Branch: `https://github.com/tenstorrent/tt-forge-fe/tree/vcanic/override_mnist`

Command: `python forge/test/benchmark/benchmark.py -m mnist_linear -bs 1 -o forge-benchmark-e2e-mnist.json`

Error:
`
                 Always | FATAL    | Shard shape must be tile sized
Traceback (most recent call last):
  File "/proj_sw/user_dev/vcanic/projects/github/tt-forge-fe/forge/test/benchmark/benchmark.py", line 138, in <module>
    main()
  File "/proj_sw/user_dev/vcanic/projects/github/tt-forge-fe/forge/test/benchmark/benchmark.py", line 132, in main
    run_benchmark(config)
  File "/proj_sw/user_dev/vcanic/projects/github/tt-forge-fe/forge/test/benchmark/benchmark.py", line 112, in run_benchmark
`

**Comment by vcanicTT** [comment]
TTIR:
`
module @MNISTLinear attributes {tt.system_desc = #tt.system_desc<[{arch = <wormhole_b0>, grid = 8x8, l1_size = 1499136, num_dram_channels = 12, dram_channel_size = 1073741824, noc_l1_address_align_bytes = 16, pcie_address_align_bytes = 32, noc_dram_address_align_bytes = 32, l1_unreserved_base = 1024, erisc_l1_unreserved_base = 1024, dram_unreserved_base = 1024, dram_unreserved_end = 1073741824, physical_cores = {worker = [ 0x0,  0x1,  0x2,  0x3,  0x4,  0x5,  0x6,  0x7,  1x0,  1x1,  1x2,  1x3,  1x4,  1x5,  1x6,  1x7,  2x0,  2x1,  2x2,  2x3,  2x4,  2x5,  2x6,  2x7,  3x0,  3x1,  3x2,  3x3,  3x4,  3x5,  3x6,  3x7,  4x0,  4x1,  4x2,  4x3,  4x4,  4x5,  4x6,  4x7,  5x0,  5x1,  5x2,  5x3,  5x4,  5x5,  5x6,  5x7,  6x0,  6x1,  6x2,  6x3,  6x4,  6x5,  6x6,  6x7,  7x0,  7x1,  7x2,  7x3,  7x4,  7x5,  7x6,  7x7] dram = [ 8x0,  9x0,  10x0,  8x1,  9x1,  10x1,  8x2,  9x2,  10x2,  8x3,  9x3,  10x3]}, supported_data_types = [<f32>, <f16>, <bf16>, <bfp_f8>, <bfp_bf8>, <bfp_f4>, <bfp_bf4>, <bfp_f2>, <bfp_bf2>, <u32>, <u16>, <u8>], supported_tile_sizes = [ 4x16,  16x16,  32x16,  4x32,  16x32,  32x32]}], [0], [3 : i32], [ 0x0x0x0]>} {
  func.func @forward(%arg0: tensor<32x784xf32> {ttir.name = "input_1"}, %arg1: tensor<784x256xf32> {ttir.name = "l1.weight"}, %arg2: tensor<256xf32> {ttir.name = "l1.bias"}, %arg3: tensor<256x32xf32> {ttir.name = "l2.weight"}, %arg4: tensor<32xf32> {ttir.name = "l2.bias"}) -> (tensor<32x32xf32> {ttir.name = "MNISTLinear.output_softmax_7"}) {
    %0 = tensor.empty() : tensor<32x256xf32>
    %1 = "ttir.matmul"(%arg0, %arg1, %0) <{operand_constraints = [#tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>]}> : (tensor<32x784xf32>, tensor<784x256xf32>, tensor<32x256xf32>) -> tensor<32x256xf32>
    %2 = tensor.empty() : tensor<32x256xf32>
    %3 = "ttir.add"(%1, %arg2, %2) <{operandSegmentSizes = array<i32: 2, 1>, operand_constraints = [#tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>]}> : (tensor<32x256xf32>, tensor<256xf32>, tensor<32x256xf32>) -> tensor<32x256xf32>
    %4 = tensor.empty() : tensor<32x256xf32>
    %5 = "ttir.relu"(%3, %4) <{operandSegmentSizes = array<i32: 1, 1>, operand_constraints = [#tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>]}> : (tensor<32x256xf32>, tensor<32x256xf32>) -> tensor<32x256xf32>
    %6 = tensor.empty() : tensor<32x32xf32>
    %7 = "ttir.matmul"(%5, %arg3, %6) <{operand_constraints = [#tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>]}> : (tensor<32x256xf32>, tensor<256x32xf32>, tensor<32x32xf32>) -> tensor<32x32xf32>
    %8 = tensor.empty() : tensor<32x32xf32>
    %9 = "ttir.add"(%7, %arg4, %8) <{operandSegmentSizes = array<i32: 2, 1>, operand_constraints = [#tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>]}> : (tensor<32x32xf32>, tensor<32xf32>, tensor<32x32xf32>) -> tensor<32x32xf32>
    %10 = tensor.empty() : tensor<32x32xf32>
    %11 = "ttir.softmax"(%9, %10) <{dimension = 1 : si32, operand_constraints = [#tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>]}> : (tensor<32x32xf32>, tensor<32x32xf32>) -> tensor<32x32xf32>
    return %11 : tensor<32x32xf32>
  }
}
`

**Comment by odjuricicTT** [comment]
@vcanicTT This might be fixed on tt-mlir main. How often does forge FE uplift? @nvukobratTT

**Comment by nvukobratTT** [comment]
> @vcanicTT This might be fixed on tt-mlir main. How often does forge FE uplift? @nvukobratTT

Daily. But we've been blocked for the last two weeks due to a few dockers and now metal uplift issues from MLIR. Should be solved soon.

**Comment by vcanicTT** [comment]
@nvukobratTT Ok, when you update the submodule, please, tell us here, so we can run these tests again and check whether the error still exists.

**Comment by nvukobratTT** [comment]
> @nvukobratTT Ok, when you update the submodule, please, tell us here, so we can run these tests again and check whether the error still exists.

Feel free to follow this PR:
- https://github.com/tenstorrent/tt-forge-fe/pull/418

You can subscribe to it, and once it's merged you'll get a notification regarding the latest MLIR uplift :))

**Comment by vcanicTT** [comment]
@nvukobratTT Ok, I subscribed
