### ISSUE TITLE
ttrt perf fails with custom artifact dir

### ISSUE THREAD

**Issue by odjuricicTT** [tenstorrent/tt-mlir#1200]
Running:
`ttrt perf mnist_sharding_tiled.ttnn --artifact-dir=/localdev/odjuricic/repos/tt-mlir/explorer-artifacts`

Fails with:
```
2024-11-08 10:23:55,616 - ERROR - ERROR: test=mnist_sharding_tiled.ttnn experienced an error with exception=the source file does not exist: 'tracy_profile_log_host.tracy'
Traceback (most recent call last):
  File "/opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/common/util.py", line 186, in copy_file
    shutil.copy2(src_file_path, dest_file_path)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/localdev/odjuricic/repos/tt-mlir/explorer-artifacts/mnist_sharding_tiled.ttnn/perf'
```

Works fine when no artifacts dir is specified.

**Comment by tapspatel** [comment]
taking a look at this today
