### ISSUE TITLE
ttrt using static paths

### ISSUE THREAD

**Issue by ttdloke** [tenstorrent/tt-mlir#294]
Traceback (most recent call last):
  File "/opt/ttmlir-toolchain/venv/bin/ttrt", line 8, in <module>
    sys.exit(main())
  File "/opt/ttmlir-toolchain/venv/lib/python3.8/site-packages/ttrt/__init__.py", line 170, in main
    args.func(args)
  File "/opt/ttmlir-toolchain/venv/lib/python3.8/site-packages/ttrt/common/api.py", line 183, in run
    system_desc, device_ids = ttrt.runtime.get_current_system_desc()
RuntimeError: filesystem error: cannot create directory: No such file or directory [/home/ubuntu/src/tt-dealer/third_party/tt-metal/src/tt-metal/tt_metal/.umd]

**Comment by ttdloke** [comment]
has to do with where virtual env is being sourced. right now it needs to be sourced from tt-mlir root dir

**Comment by tapspatel** [comment]
merged: a288b1330787d68cd59507a33aec8d195b53086a

Allows users to specify their own virtual env paths
