### ISSUE TITLE
TTRT perf throws error TypeError

### ISSUE THREAD

**Issue by odjuricicTT** [tenstorrent/tt-mlir#545]
Repro:
`ttrt perf out.ttnn`
[out.ttnn](https://drive.google.com/file/d/1xpW59AFICEhlsmpkriD1ssJy2GpK-1mR/view?usp=sharing)

Stack trace:
```
Traceback (most recent call last):
  File "/opt/ttmlir-toolchain/venv/bin/ttrt", line 8, in <module>
    sys.exit(main())
  File "/opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/__init__.py", line 42, in main
    request_api()
  File "/opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/common/api.py", line 1384, in __call__
    self.check_constraints()
  File "/opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/common/api.py", line 1099, in check_constraints
    if 'binary' not in self:
  File "/opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/common/api.py", line 1375, in __getitem__
    return getattr(self, key)
TypeError: getattr(): attribute name must be string
```

**Comment by tapspatel** [comment]
Fix was merged yesterday into: https://github.com/tenstorrent/tt-mlir/commit/0fb294e80ffde999928cc6b4e24b267d725c90b1.
